### ISSUE TITLE
Commit button not enabled

### ISSUE THREAD

**Issue by Shaoranlaos** [scm-manager/scm-editor-plugin#63]
#### Describe how to reproduce the bug

Regression with latest updated (2.10)

- Editing a file in a repository (tried in git, proberly the same for the other types)
- make changes to the file
- add a commit message
- the commit button should be enabled but remains disabled

#### Describe your SCM-Manager setup

SCM-Manager 2.30.0
scm-editor-plugin 2.10.0

Accessing SCM-Manager over a nginx proxy.

#### Which operating system, browser and versions do you use?

Centos 7

#### Further information like screenshots
![image](https://user-images.githubusercontent.com/25054970/150927420-f2960685-ed8f-4017-a6d8-bf05162dfd97.png)

**Comment by pfeuffer** [comment]
Thanks for this report. We will fix this immediately.

**Comment by pfeuffer** [comment]
We released the fixed plugin (2.10.1). Thanks again, this was a bit embarrassing.
